// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"maxblog-be-demo/internal/core"
	"maxblog-be-demo/src/model"
	"maxblog-be-demo/src/service"
)

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	db, cleanup, err := InitDB()
	if err != nil {
		return nil, nil, err
	}
	mDemo := &model.MDemo{
		DB: db,
	}
	trans := &core.Trans{
		DB: db,
	}
	logger := &core.Logger{}
	bDemo := &service.BDemo{
		MDemo:   mDemo,
		Tx:      trans,
		ILogger: logger,
	}
	injector := &Injector{
		DB:      db,
		Service: bDemo,
	}
	return injector, func() {
		cleanup()
	}, nil
}
